### ISSUE TITLE
Error : a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by masofily** [RhinoSecurityLabs/Security-Research#11]
Hello,
I followed the steps after downloading the python file. However getting the below error. Please let me know what went wrong.
Step-1: I created a file 'mydocs.docx' and have written Hello World
Step-2: I run the below command. And observed that a new file 'infected.docx' has been created at the same location and with the same content with 'mydoc.docx'. There is no other data inside 'infected.docx' file. I also received an error while running the command.
C:\Users\Sofily\Study\PythonCodes>python subdoc_injector.py -i mydoc.docx -o infected.docx -u ///127.0.0.1/subdoctest -d 100
[+] Infecting mydoc.docx
Traceback (most recent call last):
  File "subdoc_injector.py", line 227, in <module>
    main()
  File "subdoc_injector.py", line 220, in main
    infectDoc(args.infile, args.outfile, args.url, args.identifier, False)
  File "subdoc_injector.py", line 179, in infectDoc
    closepos = docx.index('/>')
TypeError: a bytes-like object is required, not 'str'

C:\Users\Sofily\Study\PythonCodes>

**Comment by kempy007** [comment]
Bump

**Comment by masofily** [comment]
Yes, now its working fine. Thanks kempy007 for your quick help.
