### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by sampablokuper** [RhinoSecurityLabs/Security-Research#17]
The files in this repository appear not to have a license specified for them.

Please can you add to the repo:

- a copy of the relevant license, and
- a notice stating who owns the copyright in the files, and stating that the copyright holder is making them available under the license above.

Ideally, please use [this license (the AGPLv3)](https://www.gnu.org/licenses/agpl-3.0.html).

Thank you.

**Comment by SpenGietz** [comment]
Added a license in!
