### ISSUE TITLE
Scanning across organization

### ISSUE THREAD

**Issue by cbchhaya** [RhinoSecurityLabs/Security-Research#24]
Would it help to be able to point this script at an organization and be able to scan all accounts underneath? Perhaps we could have a `--org` and `--role` flags and require that the user passed in has `DescribeOrganization` and `AssumeRole` permissions? That will simplify running this from a central InfoSec/Compliance account. Happy to submit a PR if this is deemed useful.

**Comment by SpenGietz** [comment]
I think this would be really cool. Would love if you could submit a PR for something like that 👍 

But do it on this repo instead: https://github.com/RhinoSecurityLabs/Cloud-Security-Research
That's the new repo for AWS/cloud research and scripts
