### ISSUE TITLE
Can access keys be picked up from env vars or profile?

### ISSUE THREAD

**Issue by cbchhaya** [RhinoSecurityLabs/Security-Research#25]
That will simplify running this without having to disclose access key and secret on CLI or in logs. `prowler`, as an example, accepts a `-p` flag for profile.

**Comment by SpenGietz** [comment]
Not sure which script you're referring to exactly, but check this out: https://github.com/RhinoSecurityLabs/Cloud-Security-Research

That's the new repo for AWS research and has a few updates scripts that do accept profiles as an argument
